### ISSUE TITLE
Version pinning of dependency of checked out package

### ISSUE THREAD

**Issue by ksuess** [mxstack/mxdev#15]
I checkout package A.
Package A has a dependency B.
Package A pins B to version v.y
Plone has a constraint on B to version v.x.
This is a conflict. "make install" fails with [^version-conflict], which is what I expect.
I can solve the conflict by pinning B in `sources.ini` 'version-overrides'. But, is this the recommended place to pin? Can I force to fullfill **any** constraints of A somehow in `sources.ini`?

[^version-conflict]: Version conflict
    ```
    INFO: pip is looking at multiple versions of plone-restapi[test] to determine which version is compatible with other requirements. This could take a while.
    ERROR: Cannot install plone-api[test]==2.0.0a4.dev0 because these package versions have conflicting dependencies.
    
    The conflict is caused by:
        plone-api[test] 2.0.0a4.dev0 depends on manuel>=1.11.2; extra == "test"
        The user requested (constraint) manuel==1.10.1
    
    To fix this you could try to:
    1. loosen the range of package versions you've specified
    2. remove package versions to allow pip attempt to solve the dependency conflict
    
    ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
    make: *** [.sentinels/install.sentinel] Error 1
    
    
    ```

**Comment by jensens** [comment]
> I can solve the conflict by pinning B in sources.ini 'version-overrides'. But, is this the recommended place to pin? Can I force to fullfill any constraints of A somehow in sources.ini?

pip has this limitation. Once pinned in constraints it is not possible to override. 
the solution and recommended way is to use `version-overrides`.

**Comment by jensens** [comment]
Under https://github.com/mxstack/mxdev#rationale -> `problem`  it is meanwhile in.
