### ISSUE TITLE
Use the current repository as a source

### ISSUE THREAD

**Issue by gforcada** [mxstack/mxdev#24]
Could it be possible to get `mxdev` to have a way, i.e

```ini
[settings]
use-local = True
use-local-extras = test
```
_(naming can be bikesheeded 🚲 )_ 😄 

This option(s) would make the repository the configuration is in to be used as a source.

The use case would be: I add a `mxdev.ini` configuration on `plone.batching` where I reference Plone 6.0.0 `constraints.txt` but `plone.batching` is used from the git checkout.

This would avoid to have to specify the branch, and specially it would play nice in CI environments: run `mxdev` on CI to get an up-to-date and working virtual environment where to run tests and other stuff 🍀 

Is that already possible and I'm just not seeing it? 🤔

**Comment by rnixx** [comment]
you can add ``-e .`` to requirements.txt

**Comment by gforcada** [comment]
@rnixx thanks! 🤦🏾 oh my, I used that 1000 times 😅

**Comment by rnixx** [comment]
@gforcada see #29 -> For convenience ;)
