### ISSUE TITLE
main package not commented out in constraints

### ISSUE THREAD

**Issue by gforcada** [mxstack/mxdev#33]
I have a global constraints file with all our packages and Plone ones:

```txt
freitag.one == 1.2.3
freitag.two == 1.2.3
freitag.three == 1.2.3
...
Products.CMFPlone == 5.2.12
...
```

Now, when adding `mxdev` support to `freitag.one` which needs `freitag.two` I add:

```ini
[settings]
...
main-package = -e .[test]
...
```

But on the generated `constraints-mxdev.txt` `freitag.one` is not being commented out:

```txt
freitag.one == 1.2.3
# freitag.two == 1.2.3 -> mxdev disabled (source)
# freitag.three == 1.2.3 -> mxdev disabled (source)
```

`pip` reports that as:

`ERROR: Could not find a version that satisfies the requirement freitag-one[test] 1.2.4.dev0`

Commenting out that line on `constraints-mxdev.txt` makes `pip` happy and installs all packages 🎉

**Comment by rnixx** [comment]
Hi,

this one is tricky. At `mxdev` runtime we have no information about the main package name. So we have several options. We can parse the package name from `setup.py`, `pyproject.toml` or `setup.cfg`, which would be convenient but hard to get reliable. Another solution would be to introduce another setting for `mx.ini`, maybe named `ignore-constraints`, with the tradeoff that we have another setting. Any other ideas how to solve this?

**Comment by rnixx** [comment]
Oh, we already have an ignores setting -> https://github.com/mxstack/mxdev#ignores

**Comment by gforcada** [comment]
Cool, maybe we should mention that on the documentation, i.e. next to the `main-package` setting.

Indeed, I skimmed over the documentation and did not read it fully, but when I saw the `ignores` option I thought it would be for optional dependencies, and things like that, not for my use case 😅 

Thanks!

**Comment by rnixx** [comment]
Docs are already extended ;) https://github.com/mxstack/mxdev/commit/98d4a14f23da6cadd66e0619930f98535122dd16
