### ISSUE TITLE
Document vcs options

### ISSUE THREAD

**Issue by pbauer** [mxstack/mxdev#38]
The option `vcs` when defining a package allows to specify various formats including `fs` (filesystem, i.e. running it will not pull or update). 
Supported options are bzr, darcs, fs, git, gitsvn, hg and svn

Example:

```ini
[my.package]
path = ${settings:directory}/sources/my.package
url = my.package
extras = test
vcs = fs
```

**Comment by pbauer** [comment]
When combining with the `target` setting you can get a setup as what I used to use with `buildout` and `mr.developer`: 
Checkouts end up in `/sources` whereas packages that are part of the project-repository are in `/src`.

Example:

```ini
[my.package]
path = ${settings:directory}/src/my.package
url = my.package
extras = test
vcs = fs
target = src

[my.second.package]
path = ${settings:directory}/src/my.second.package
url = my.second.package
extras = test
vcs = fs
target = src

[collective.eeafaceted.z3ctable]
url = https://github.com/collective/collective.eeafaceted.z3ctable.git
pushurl = git@github.com:collective/collective.eeafaceted.z3ctable.git
branch = plone6
```

**Comment by rnixx** [comment]
> When combining with the `target` setting you can get a setup as what I used to use with `buildout` and `mr.developer`: Checkouts end up in `/sources` whereas packages that are part of the project-repository are in `/src`.

This works OOTB?

**Comment by jensens** [comment]
We (so, in fact @zworkb) copied it from mr.developer, so well probably it is there.

**Comment by rnixx** [comment]
Ok, then let's add some docs ;)
