### ISSUE TITLE
Support git push URLs

### ISSUE THREAD

**Issue by jensens** [mxstack/mxdev#4]
Add a URL for pushing like with `git remote set-url --push origin SOMEURL`. 

In `sources.ini` this should look like:

``` INI
# ...
[my.pkg]
url = git+https://github.com/orga/repo
push = git+ssh://git@github.com/orga/repo
```

Easiest would be to add this feature to libvcs first and then use it. I opened a request https://github.com/vcs-python/libvcs/issues/297

**Comment by avoinea** [comment]
@jensens Any news on this?

**Comment by jensens** [comment]
No time until now, but it will happen.

**Comment by jensens** [comment]
see #16
