### ISSUE TITLE
Cannot specify revision

### ISSUE THREAD

**Issue by pbauer** [mxstack/mxdev#40]
When I specify a revision
```
[yafowil.plone]
url = https://github.com/bluedynamics/yafowil.plone.git
pushurl = git@github.com:bluedynamics/yafowil.plone.git
rev = 34c1753
```
I get "Cannot specify both branch (main) and rev/revision (34c1753) in source for yafowil.plone" since `main` is the default-value.

**Comment by rnixx** [comment]
@pbauer btw, why do you need to pin a revision of yafowil.plone? is there a bug in a release or a recent release missing?

**Comment by pbauer** [comment]
https://github.com/bluedynamics/yafowil.plone/pull/48
