### ISSUE TITLE
Migrate from `pkg_resources` to `importlib_resources`

### ISSUE THREAD

**Issue by stevepiercy** [mxstack/mxdev#42]
[Python 3.12 removed the deprecated `pkg_resources` from being installed when creating a virtual environment](https://docs.python.org/3/whatsnew/3.12.html). mxdev needs to [migrate to `importlib_resources`](https://importlib-resources.readthedocs.io/en/latest/migration.html).

See https://community.plone.org/t/error-while-running-make-install-command/19114

**Comment by jensens** [comment]
Got it, it is 
- `importlib.metadata` to load entry_points (unstable API in standard library, how ugly, but well...)
- https://pypi.org/project/packaging/ for `pkg_resources.Requirement.parse`

**Comment by jensens** [comment]
Fixed, release next.
