### ISSUE TITLE
Packages with capital names do not get ignored when checked out

### ISSUE THREAD

**Issue by mauritsvanrees** [mxstack/mxdev#45]
See https://github.com/plone/buildout.coredev/pull/931.  There I needed to do a [manual fix](https://github.com/plone/buildout.coredev/pull/931/commits/ece7b946008472a034b5763c37d5652d604b4b80) because `Plone` and `Products.CMFPlone` were checked out, but still pinned in the constraints.

**Comment by jensens** [comment]
@mauritsvanrees fixed and released

**Comment by petschki** [comment]
@mauritsvanrees there's one more fix for capital names here https://github.com/mxstack/mxdev/pull/48
